### PR TITLE
Email template update

### PR DESCRIPTION
**Pull request by AshakaE**
Updates email template with new design

image

## Linked issues

 closes https://github.com/EveripediaNetwork/issues/issues/896

### CODE REVIEW

**Comment by Simplypheyie96** [comment]
there is no link to preview @AshakaE 
also, here is a link to the pattern itself: https://www.figma.com/file/wosuJaHeV318k1ON82CZpo/%F0%9F%A7%A0-IQ.WIKI?node-id=12966%3A126580&t=TCByEaXGJQohlu1p-1

**Comment by kesar** [comment]
> there is no link to preview @AshakaE also, here is a link to the pattern itself: https://www.figma.com/file/wosuJaHeV318k1ON82CZpo/%F0%9F%A7%A0-IQ.WIKI?node-id=12966%3A126580&t=TCByEaXGJQohlu1p-1

for backend its a bit more complicated to get a link, I guess we could merge it and test it on production, or @AshakaE can help you to get a notification in development stage 👍🏻

**Comment by AshakaE** [comment]
> > there is no link to preview @AshakaE also, here is a link to the pattern itself: https://www.figma.com/file/wosuJaHeV318k1ON82CZpo/%F0%9F%A7%A0-IQ.WIKI?node-id=12966%3A126580&t=TCByEaXGJQohlu1p-1
> 
> for backend its a bit more complicated to get a link, I guess we could merge it and test it on production, or @AshakaE can help you to get a notification in development stage 👍🏻 

I disabled notifications in production so we don't send the wrong design, I'll merge to development for testing

**Review by kesar — APPROVED** [review]

**Comment by Softdev1** [comment]
now, that it has been merged I will do multiple testing  on it

**Comment by Simplypheyie96** [comment]
@AshakaE image size looks scaled. We need to make the image the same ratio as the wiki images.
image
Typo mistake:
image

**Comment by Simplypheyie96** [comment]
i also think we need to make a dark mode because I tested on my phone and the dark mode looks something like this. 
image
so here is the link to the dark mode 
https://www.figma.com/file/wosuJaHeV318k1ON82CZpo/%F0%9F%A7%A0-IQ.WIKI?node-id=13008%3A99447&t=3blPuCC46NnK1XUO-1

**Pull request merged**
