### PR TITLE
Profile review

### PR DESCRIPTION
**Pull request by AshakaE**
# Optimize profile queries

## Notes or observations

_Graphql queries call whole db table even if one field is slected, I've added a method to query db by only what was selected in the graphql query_

## Linked issues

closes https://github.com/EveripediaNetwork/issues/issues

### CODE REVIEW

**Comment by AshakaE** [comment]
Giving this a try to see improvements

**Comment by AshakaE** [comment]
Getting under 300ms

**Comment by kesar** [comment]
> Graphql queries call whole db table even if one field is slected, I've added a method to query db by only what was selected in the graphql query

what do u mean by whole db table? if that's the case then its because of needed indexes, not because fields (unless those fields are joins)

**Comment by AshakaE** [comment]
> > Graphql queries call whole db table even if one field is slected, I've added a method to query db by only what was selected in the graphql query
> 
> what do u mean by whole db table? if that's the case then its because of needed indexes, not because fields (unless those fields are joins)

I mean, it selects all the columns by default regardless of what field you query for in the grapql

**Pull request merged**
