### PR TITLE
Email iterations

### PR DESCRIPTION
**Pull request by AshakaE**
# Email Iterations

_Switch header from only PNG to include HTML tags for logo mission statement_
_Download button on image appears by default, enabled by Gmail_
_Adds grey background to the get more from IQ.Wiki section_
_Serve static assets from server_

## How should this be tested?

1. in Dev, wait for night fall to test dark mode(specifically Gmail)
## Notes or observations

image

## Linked issues

 closes https://github.com/EveripediaNetwork/issues/issues/933

### CODE REVIEW

**Review by Simplypheyie96 — COMMENTED** [review]
I think we might have to forfeit the dark mode thingy. it is not working out.

**Comment by AshakaE** [comment]
> I think we might have to forfeit the dark mode thingy. it is not working out.

I don't think it's possible because when someone edits a wiki at night and subscribers have dark mode on, it will still show up

**Comment by AshakaE** [comment]
> I think we might have to forfeit the dark mode thingy. it is not working out.

The real issue is not being able to tweak Gmail dark mode

**Comment by kesar** [comment]
in theory gmail support dark mode

https://www.litmus.com/blog/the-ultimate-guide-to-dark-mode-for-email-marketers/

and that should be not related to whom write the wiki but who receive the email

**Comment by AshakaE** [comment]
> in theory gmail support dark mode
> 
> https://www.litmus.com/blog/the-ultimate-guide-to-dark-mode-for-email-marketers/
> 
> and that should be not related to whom write the wiki but who receive the email

The methods from this tutorial are presently implemented, tested locally, and Gmail still doesn't take the chages.

**Comment by kesar** [comment]
then lets not overcomplicate this. lets code a template email that will be readable in dark mode (adding a bg)

Captura de pantalla 2022-12-27 a las 13 03 24

for example this one has a grey / white bg that ensures that text is gonna be readable even if i would be in dark mode

**Comment by Simplypheyie96** [comment]
> > I think we might have to forfeit the dark mode thingy. it is not working out.
> 
> I don't think it's possible because when someone edits a wiki at night and subscribers have dark mode on, it will still show up

the design has been made then, its left to you guys

**Pull request merged**
