### PR TITLE
Cache queries

### PR DESCRIPTION
**Pull request by AshakaE**
# Cache queries

_Added for only a `activities(1 min)` and `wikis (10 sec)`_

## How should this be tested?

1. In dev | prod, to monitor any improvements

## Linked issues

closes https://github.com/EveripediaNetwork/issues/issues/984

### CODE REVIEW

**Comment by kesar** [comment]
its a good start, lets add a name to see if later they can remove it from indexer doing something like: await dataSource.queryResultCache.remove(["users_admins"])

cache: {
        id: "activity",
        milliseconds: 60000,
    },

we can start w 1m and if clearing works fine we could do a 1h cache

**Comment by kesar** [comment]
also make sure pagination works as expected, in case caching does something weird

**Comment by AshakaE** [comment]
> its a good start, lets add a name to see if later they can remove it from indexer doing something like: await dataSource.queryResultCache.remove(["users_admins"])
> 
> cache: { id: "activity", milliseconds: 60000, },
> 
> we can start w 1m and if clearing works fine we could do a 1h cache

**Comment by AshakaE** [comment]
> its a good start, lets add a name to see if later they can remove it from indexer doing something like: await dataSource.queryResultCache.remove(["users_admins"])
> 
> cache: { id: "activity", milliseconds: 60000, },
> 
> we can start w 1m and if clearing works fine we could do a 1h cache

fwiw, I did not notice the cache storing `Activity.user` as a part of it, also why it runs a separate query to retrieve user

**Review by kesar — APPROVED** [review]

**Pull request merged**
