### PR TITLE
Feature/delete user

### PR DESCRIPTION
**Pull request by AshakaE**
# Soft delete user

_A new column `active` is added on the user table, `default: true`, when a user gets banned, their active status changes to false. A separate guard is added to some certain mutation endpoints to check if the user's active status is true otherwise the action fails_

## How should this be tested?

1. `banUserById` _Admin only_
image

2. A banned ID cannot post wikis 
image

## Linked issues

closes https://github.com/EveripediaNetwork/issues/issues/632

### CODE REVIEW

**Comment by kesar** [comment]
once its banned what happens? what's the purpose?

**Comment by AshakaE** [comment]
> once its banned what happens? what's the purpose?

They can't perform actions like createProfile or post wikis. It's to support the admin panel, ordinarily if user address gets deleted it will affect wiki structure because of the relation

**Comment by kesar** [comment]
> > once its banned what happens? what's the purpose?
> 
> They can't perform actions like createProfile or post wikis. It's to support the admin panel, ordinarily if user address gets deleted it will affect wiki structure because of the relation

ok, you forgot to add guard to pinImage  👍🏻 besides that everything looks good

**Comment by AshakaE** [comment]
> > > once its banned what happens? what's the purpose?
> > 
> > 
> > They can't perform actions like createProfile or post wikis. It's to support the admin panel, ordinarily if user address gets deleted it will affect wiki structure because of the relation
> 
> ok, you forgot to add guard to pinImage 👍🏻 besides that everything looks good

Not all queries come with user address so it's a bit difficult to track on pinImage

**Review by Softdev1 — APPROVED** [review]

**Pull request merged**
