### PR TITLE
Optimize image upload

### PR DESCRIPTION
**Pull request by AshakaE**
# Optimizing images before pinning

_Images are sent to the api and processed with a package called [sharp](https://sharp.pixelplumbing.com/api-output). All images are converted to webp to get a reduced file size_

## How should this be tested?

1. [Postman](https://documenter.getpostman.com/view/13541794/UVsMvmHZ)

## Notes or observations

_[sharp](https://sharp.pixelplumbing.com/api-output#webp) has other methods to process images but I found the best method for optimizing images to be `.webp` while retaining the same visual quality._

## Linked issues

 closes [#299](https://github.com/EveripediaNetwork/issues/issues/299)

### CODE REVIEW

**Comment by AshakaE** [comment]
> looking promising! perhaps can we also resize it to a max resolution?

I found a package that can do this surprisingly well, although I haven't tested it [UpscalerJS](https://github.com/thekevinscott/UpscalerJS)


> we need to investigate a proper value that looks good in our site 👍👍 any suggestion is welcome

I'll check with front end to get an idea of the best values /resolution, one thing with the sharp package is when it gets a really high res image of 7mb, is converts to webp with a size not up to 1mb while retaining visual quality 🤯 


_There's another package [image-size](https://www.npmjs.com/package/image-size) that detects dimensions, could be used to add more control 💡_

**Comment by kesar** [comment]
> > looking promising! perhaps can we also resize it to a max resolution?
> 
> I found a package that can do this surprisingly well, although I haven't tested it [UpscalerJS](https://github.com/thekevinscott/UpscalerJS)
> 
> > we need to investigate a proper value that looks good in our site 👍👍 any suggestion is welcome
> 
> I'll check with front end to get an idea of the best values /resolution, one thing with the sharp package is when it gets a really high res image of 7mb, is converts to webp with a size not up to 1mb while retaining visual quality 🤯
> 
> _There's another package [image-size](https://www.npmjs.com/package/image-size) that detects dimensions, could be used to add more control 💡_

you can still use sharp isnt? 

.resize({ width: 1024 })

**Comment by AshakaE** [comment]
> > > looking promising! perhaps can we also resize it to a max resolution?
> > 
> > 
> > I found a package that can do this surprisingly well, although I haven't tested it [UpscalerJS](https://github.com/thekevinscott/UpscalerJS)
> > > we need to investigate a proper value that looks good in our site 👍👍 any suggestion is welcome
> > 
> > 
> > I'll check with front end to get an idea of the best values /resolution, one thing with the sharp package is when it gets a really high res image of 7mb, is converts to webp with a size not up to 1mb while retaining visual quality 🤯
> > _There's another package [image-size](https://www.npmjs.com/package/image-size) that detects dimensions, could be used to add more control 💡_
> 
> you can still use sharp isnt?
> 
> .resize({ width: 1024 })

Yes, I was looking at the quality as well 🤔

**Comment by AshakaE** [comment]
Except we exclusively as users to upload square image, doing `.resize({ width: 1024 })` will mostly likely crop out some parts of the image.  NB.😅 UpscalerJS is taking a lot of time

**Comment by kesar** [comment]
if its too complex, we can start w the webp initially. if you see improvements from 7MB to 1MB thats pretty good 👍🏻

**Comment by AshakaE** [comment]
I see what you mean now, the resize method would handle dimensions and not file size, and using webp gives us a much smaller file size which is great. If we wanted to use a fixed dimension and retain its aspect ratio, then we'll do some extra manipulation

**Review by philipep-galdino — APPROVED** [review]
here it seems to do what its intended to. and its a nice code, tho! good job, man 👍🏾

**Pull request merged**
